services:
  postgres:
    image: postgres:16-alpine
    container_name: qltc-postgres-prod
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - qltc-postgres-prod-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    container_name: qltc-backend-prod
    restart: unless-stopped

    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: ${BE_PORT}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_SYNC: "false"

    ports:
      - "${BE_PORT}:${BE_PORT}"

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: qltc-frontend-prod
    restart: unless-stopped

    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: ${FE_PORT}

    ports:
      - "${FE_PORT}:${FE_PORT}"

    depends_on:
      - backend

volumes:
  qltc-postgres-prod-data: